version: '3.8'

services:
  # Node.js service
  app:
    build: .
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    command: sh -c "npm install && npm run start"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/Blogdb

  # MongoDB service
  mongo:
    image: mongo:5
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
